export const dashboards = [
  {
    slug: "executive",
    title: "CEO / Executive",
    titleAr: "تنفيذي / CEO",
    description: "Strategy posture, initiative health, KPI attainment, and top escalations.",
    descriptionAr: "موقف الاستراتيجية وصحة المبادرات وتحقيق المؤشرات وأبرز التصعيدات.",
    icon: "tabler:crown",
  },
  {
    slug: "pillar",
    title: "Pillar",
    titleAr: "ركيزة",
    description: "Pillar roll-up health, initiative coverage, KPI scorecard, and risks.",
    descriptionAr: "صحة الركيزة المجمعة وتغطية المبادرات وبطاقة المؤشرات والمخاطر.",
    icon: "tabler:layers-subtract",
  },
  {
    slug: "initiative-health",
    title: "Initiative Health",
    titleAr: "صحة المبادرات",
    description: "System-calculated health score drivers across KPIs, milestones, and risks.",
    descriptionAr: "محركات درجة الصحة المحسوبة للنظام عبر المؤشرات والمعالم والمخاطر.",
    icon: "tabler:activity-heartbeat",
  },
  {
    slug: "kpi-performance",
    title: "KPI Performance",
    titleAr: "أداء المؤشرات",
    description: "Target vs actual, variance distribution, freshness, and top movers.",
    descriptionAr: "المستهدف مقابل الفعلي وتوزيع الانحراف والحداثة وأبرز المتغيرات.",
    icon: "tabler:chart-line",
  },
  {
    slug: "project-execution",
    title: "Project Execution",
    titleAr: "تنفيذ المشاريع",
    description: "Milestone completion, blockers/dependencies, and delivery confidence.",
    descriptionAr: "اكتمال المعالم والعوائق/الاعتمادات وثقة التنفيذ.",
    icon: "tabler:timeline",
  },
  {
    slug: "manager",
    title: "Manager / Department",
    titleAr: "مدير / إدارة",
    description: "Owned initiatives/projects, at-risk KPIs, and pending actions.",
    descriptionAr: "المبادرات/المشاريع المملوكة، مؤشرات معرضة للمخاطر، وإجراءات معلّقة.",
    icon: "tabler:users-group",
  },
  {
    slug: "risk-escalation",
    title: "Risk & Escalation",
    titleAr: "المخاطر والتصعيد",
    description: "Severity distribution, aging, critical escalations, and mitigation owners.",
    descriptionAr: "توزيع الخطورة والعمر والتصعيدات الحرجة ومالكي التخفيف.",
    icon: "tabler:shield-exclamation",
  },
  {
    slug: "governance",
    title: "Strategy Change & Governance",
    titleAr: "تغيير الاستراتيجية والحوكمة",
    description: "Auditability, change requests, approval times, and publish controls.",
    descriptionAr: "قابلية التدقيق وطلبات التغيير وأزمنة الموافقات وضوابط النشر.",
    icon: "tabler:gavel",
  },
] as const;
